# 保存路径
g_save_path: "."
g_save_path_color: "./color"
g_save_path_depth: "./depth"

# 深度图转换时的最大深度
g_max_depth : 100.0

# blender 渲染参数，可以不用管
g_engine_type : "BLENDER_EEVEE"
g_use_film_transparent : false 
g_rgb_color_mode : "RGBA"
g_rgb_color_depth : "16"
g_rgb_file_format : "PNG"
g_depth_color_mode : "RGBA"
g_depth_color_depth : "16"
g_depth_file_format : "OPEN_EXR"
g_depth_use_overwrite : true
g_depth_use_file_extension : true
use_gpu : false
g_scale_space : "RENDER_SIZE"
g_depth_clip_start : 0.1
g_depth_clip_end : 100
g_rotation_mode : "XYZ"


# 主要就是设置一下渲染的大小，和相机的fov
g_resolution_x : 1920
g_resolution_y : 1080
g_resolution_percentage : 100
g_cam_fov : 109.18822688429465



